# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1234, 626)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 541, 361))
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 50, 481, 361))
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.Btn_Connect = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Connect.setGeometry(QtCore.QRect(680, 430, 141, 51))
        self.Btn_Connect.setIconSize(QtCore.QSize(40, 40))
        self.Btn_Connect.setObjectName("Btn_Connect")
        self.Btn_Start = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Start.setGeometry(QtCore.QRect(460, 430, 141, 51))
        self.Btn_Start.setIconSize(QtCore.QSize(40, 40))
        self.Btn_Start.setObjectName("Btn_Start")
        self.Btn_nhapthongsokho = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_nhapthongsokho.setGeometry(QtCore.QRect(680, 510, 271, 51))
        self.Btn_nhapthongsokho.setIconSize(QtCore.QSize(40, 40))
        self.Btn_nhapthongsokho.setObjectName("Btn_nhapthongsokho")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 510, 161, 51))
        self.label_3.setObjectName("label_3")
        self.ln_vitri = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_vitri.setGeometry(QtCore.QRect(500, 510, 101, 41))
        self.ln_vitri.setObjectName("ln_vitri")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 0, 91, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(680, 0, 121, 41))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1234, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Connect.setText(_translate("MainWindow", "Connect"))
        self.Btn_Start.setText(_translate("MainWindow", "Start"))
        self.Btn_nhapthongsokho.setText(_translate("MainWindow", "Nhập thông số kho"))
        self.label_3.setText(_translate("MainWindow", "Nhập vị trí"))
        self.label_4.setText(_translate("MainWindow", "Map"))
        self.label_5.setText(_translate("MainWindow", "Camera"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
